[PHP]

; Fuseau horaire de l'application
date.timezone = Europe/Paris

; Mémoire maximale disponible pour PHP
memory_limit = 256M

; Taille maximale des fichiers envoyés
upload_max_filesize = 64M
post_max_size = 64M

; Affichage des erreurs en développement
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; OPcache
opcache.enable = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0